module.exports = {
  id: "number",
  name: "string",
  alternative_text: "string",
  caption: "string",
  width: "number",
  height: "number",
  formats: "string",
  hash: "string",
  ext: "string",
  mime: "string",
  size: "number",
  url: "string",
  preview_url: "string",
  provider: "string",
  provider_metadata: "string",
  created_at: "datetime",
  updated_at: "datetime",
  created_by_id: "number",
  updated_by_id: "number",
};
